funny_books = [
    {"id": 100, "title": "Ormar på ett plan: En Python-berättelse", "author": "Guido van Rossum"},
    {"id": 101, "title": "The Pragmatic Procrastinator", "author": "Dave Thomasson"},
    {"id": 102, "title": "Python för folk som hatar ormar", "author": "Monty Pythonsson"},
    {"id": 103, "title": "Why Your Tests Are Lying to You", "author": "Kent Backdoor"},
    {"id": 104, "title": "Playwright: Click It Till You Make It", "author": "Microslop Browserdóttir"},
    {"id": 105, "title": "Git Blame and Other Ways to Lose Friends", "author": "Linus Torvalds"},
    {"id": 106, "title": "Learn Python in 21 Years", "author": "Sams Teachyourself"},
    {"id": 107, "title": "Agile Is a Feeling", "author": "Jeff Sutherland"},
    {"id": 108, "title": "Playwright: Waiting for Selectors", "author": "Samuel Barclay Beckett"},
    {"id": 109, "title": "Stack Overflow: A Love Story", "author": "Copy Pasta"},
    {"id": 110, "title": "My First Regex (And Last)", "author": "Larry Wallström"},
    {"id": 111, "title": "The Developer Who Knew Nothing", "author": "George R.R. Martin"},
    {"id": 112, "title": "The Bugs are Coming", "author": "George R.R. Martin"},
]